export const SERVER = "http://localhost:4000/data-personal"

export const GET_PERSONAL_BEGIN = "GET_PERSONAL_BEGIN";
export const GET_PERSONAL_SUCCESS = "GET_PERSONAL_SUCCESS";
export const GET_PERSONAL_FAIL = "GET_PERSONAL_FAIL";

export const GET_DETAIL_BEGIN = "GET_DETAIL_BEGIN";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAIL = "GET_DETAIL_FAIL";


export const POST_DATA_BEGIN = "POST_DATA_BEGIN"
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS"
export const POST_DATA_FAIL = "POST_DATA_FAIL"

// export const DELETE_DATA_BEGIN = "DELETE_DATA_BEGIN"
// export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
// export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL"